### ISSUE TITLE
Need data storage for "boss" images

### ISSUE THREAD

**Issue by yoshi-isle** [yoshi-isle/PvM-Highscores-Discord-Bot#1]

**Comment by 3ear** [comment]
I would just pull images from osrs wiki

**Comment by yoshi-isle** [comment]
Probably the best choice if we can assume they stay the same for a while

**Comment by 3ear** [comment]
i bet the paths will but the image will get updated as necessary if they make graphical changes. Could just make an interface that can handle pulling from web or from local storage
