### ISSUE TITLE
On update, populate data from DB -> Google Sheet

### ISSUE THREAD

**Issue by yoshi-isle** [yoshi-isle/PvM-Highscores-Discord-Bot#16]
People might want to see where they rank at a certain activity, but aren't in the top 3. could have an excel sheet showing every placement if people want. I do not want to show more than 3 spots on the embeds, and i also dont want to make a website lol

**Comment by 3ear** [comment]
what if you add command to bot to lookup username (e.g !pb duke yoshi) and it would return your ranking (maybe even support listing all rankings
